services:
  # 1. Nosso Banco de Dados MySQL
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Pega do .env
      MYSQL_DATABASE: ${DB_NAME} # Pega do .env
    ports:
      - "3306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql

  # 2. Nosso Backend (API)
  api:
    build:
      context: . # Usa o Dockerfile na pasta atual
      args:
        # --- ESTA É A CORREÇÃO ---
        # "Passa" a DATABASE_URL do .env para dentro do build
        - DATABASE_URL=${DATABASE_URL}
    restart: always
    ports:
      - "3000:3000" 
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db 
    command: >
      sh -c "npx prisma migrate deploy && 
             npx prisma db seed && 
             npm start"
             
volumes:
  mysql-data: